package viewConfiguracion;

import java.awt.Color;
import view.Menu;

/**
 *
 * @author julia
 */
public class ConfiguracionView extends javax.swing.JFrame {

    public ConfiguracionView() {
        initComponents();
        grupoBotones.add(botonNo);
        grupoBotones.add(botonSi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonSi = new javax.swing.JRadioButton();
        botonNo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ActualizarDatosUsuario = new javax.swing.JButton();
        TextActualizaUsuario = new javax.swing.JTextField();
        TextActualizaUsuario1 = new javax.swing.JTextField();
        TextActualizaUsuario2 = new javax.swing.JTextField();
        TextActualizaUsuario3 = new javax.swing.JTextField();
        TextActualizaUsuario4 = new javax.swing.JTextField();
        TextActualizaUsuario5 = new javax.swing.JTextField();
        TextActualizaUsuario6 = new javax.swing.JTextField();
        TextActualizaUsuario7 = new javax.swing.JTextField();
        TextActualizaUsuario8 = new javax.swing.JTextField();
        TextActualizaUsuario9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(162, 217, 206));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuración");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        jPanel3.setBackground(new java.awt.Color(245, 245, 220));

        botonSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SI");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NO");

        jPanel4.setBackground(new java.awt.Color(210, 180, 140));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Modo oscuro: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(210, 180, 140));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar Datos: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        ActualizarDatosUsuario.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        ActualizarDatosUsuario.setForeground(new java.awt.Color(153, 153, 153));
        ActualizarDatosUsuario.setText("Actualizar Datos");
        ActualizarDatosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarDatosUsuarioActionPerformed(evt);
            }
        });

        TextActualizaUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario.setText("Usuario");
        TextActualizaUsuario.setBorder(null);
        TextActualizaUsuario.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuarioMousePressed(evt);
            }
        });
        TextActualizaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuarioActionPerformed(evt);
            }
        });

        TextActualizaUsuario1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario1.setText("Contraseña Actual");
        TextActualizaUsuario1.setBorder(null);
        TextActualizaUsuario1.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario1MousePressed(evt);
            }
        });
        TextActualizaUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario1ActionPerformed(evt);
            }
        });

        TextActualizaUsuario2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario2.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario2.setText("Confirmar Contraseña");
        TextActualizaUsuario2.setBorder(null);
        TextActualizaUsuario2.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario2MousePressed(evt);
            }
        });
        TextActualizaUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario2ActionPerformed(evt);
            }
        });

        TextActualizaUsuario3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario3.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario3.setText("Contraseña Actual");
        TextActualizaUsuario3.setBorder(null);
        TextActualizaUsuario3.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario3MousePressed(evt);
            }
        });
        TextActualizaUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario3ActionPerformed(evt);
            }
        });

        TextActualizaUsuario4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario4.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario4.setText("Nueva Contraseña");
        TextActualizaUsuario4.setBorder(null);
        TextActualizaUsuario4.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario4MousePressed(evt);
            }
        });
        TextActualizaUsuario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario4ActionPerformed(evt);
            }
        });

        TextActualizaUsuario5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario5.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario5.setText("Confirmar Contraseña");
        TextActualizaUsuario5.setBorder(null);
        TextActualizaUsuario5.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario5MousePressed(evt);
            }
        });
        TextActualizaUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario5ActionPerformed(evt);
            }
        });

        TextActualizaUsuario6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario6.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario6.setText("Nuevo Nombre");
        TextActualizaUsuario6.setBorder(null);
        TextActualizaUsuario6.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario6MousePressed(evt);
            }
        });
        TextActualizaUsuario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario6ActionPerformed(evt);
            }
        });

        TextActualizaUsuario7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario7.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario7.setText("Correo");
        TextActualizaUsuario7.setBorder(null);
        TextActualizaUsuario7.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario7MousePressed(evt);
            }
        });
        TextActualizaUsuario7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario7ActionPerformed(evt);
            }
        });

        TextActualizaUsuario8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario8.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario8.setText("Contraseña Actual");
        TextActualizaUsuario8.setBorder(null);
        TextActualizaUsuario8.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario8MousePressed(evt);
            }
        });
        TextActualizaUsuario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario8ActionPerformed(evt);
            }
        });

        TextActualizaUsuario9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TextActualizaUsuario9.setForeground(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario9.setText("Confirmar Contraseña");
        TextActualizaUsuario9.setBorder(null);
        TextActualizaUsuario9.setCaretColor(new java.awt.Color(204, 204, 204));
        TextActualizaUsuario9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextActualizaUsuario9MousePressed(evt);
            }
        });
        TextActualizaUsuario9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextActualizaUsuario9ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(104, 104, 104));
        jButton1.setText("Volver...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setText("Actualizar Usuario:");

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setText("Cambiar Contraseña:");

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setText("Actualizar Perfil:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSi)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonNo)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(147, 147, 147)
                                .addComponent(ActualizarDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextActualizaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextActualizaUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextActualizaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextActualizaUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextActualizaUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextActualizaUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextActualizaUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextActualizaUsuario8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextActualizaUsuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextActualizaUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonSi)
                    .addComponent(botonNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TextActualizaUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextActualizaUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextActualizaUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextActualizaUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextActualizaUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ActualizarDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextActualizaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextActualizaUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(TextActualizaUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextActualizaUsuario8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextActualizaUsuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 810, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiActionPerformed

    private void ActualizarDatosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarDatosUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarDatosUsuarioActionPerformed

    private void TextActualizaUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuarioMousePressed
        if(TextActualizaUsuario.getText().equals("Usuario")){
            TextActualizaUsuario.setText("");
            TextActualizaUsuario.setForeground(Color.black);
        }
    }//GEN-LAST:event_TextActualizaUsuarioMousePressed

    private void TextActualizaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuarioActionPerformed

    private void TextActualizaUsuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario1MousePressed

    private void TextActualizaUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario1ActionPerformed

    private void TextActualizaUsuario2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario2MousePressed

    private void TextActualizaUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario2ActionPerformed

    private void TextActualizaUsuario3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario3MousePressed

    private void TextActualizaUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario3ActionPerformed

    private void TextActualizaUsuario4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario4MousePressed

    private void TextActualizaUsuario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario4ActionPerformed

    private void TextActualizaUsuario5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario5MousePressed

    private void TextActualizaUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario5ActionPerformed

    private void TextActualizaUsuario7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario7MousePressed

    private void TextActualizaUsuario7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario7ActionPerformed

    private void TextActualizaUsuario8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario8MousePressed

    private void TextActualizaUsuario8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario8ActionPerformed

    private void TextActualizaUsuario9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario9MousePressed

    private void TextActualizaUsuario9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextActualizaUsuario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextActualizaUsuario6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario6ActionPerformed

    private void TextActualizaUsuario6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextActualizaUsuario6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextActualizaUsuario6MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarDatosUsuario;
    private javax.swing.JTextField TextActualizaUsuario;
    private javax.swing.JTextField TextActualizaUsuario1;
    private javax.swing.JTextField TextActualizaUsuario2;
    private javax.swing.JTextField TextActualizaUsuario3;
    private javax.swing.JTextField TextActualizaUsuario4;
    private javax.swing.JTextField TextActualizaUsuario5;
    private javax.swing.JTextField TextActualizaUsuario6;
    private javax.swing.JTextField TextActualizaUsuario7;
    private javax.swing.JTextField TextActualizaUsuario8;
    private javax.swing.JTextField TextActualizaUsuario9;
    private javax.swing.JRadioButton botonNo;
    private javax.swing.JRadioButton botonSi;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
